### ISSUE TITLE
Bug in DelogoHD when Pos Y is an odd number in LogoScan

### ISSUE THREAD

**Issue by Reel-Deal** [msg7086/DelogoHD#3]
There's a bug in DelogoHD when Pos Y is an odd number in LogoScan. The result looks like it's embossed. This only happens in DelogoHD, the original Delogo and aviutl's Delogo work fine.

Here's a sample of what it looks like:
![test](https://user-images.githubusercontent.com/3104705/133920238-73895e2f-9afb-4068-aa86-06da37d645ad.png)

In addition I prepared a package that includes the video, the working and not working lgd, and the settings used in LogoScan.

- [delogohd-bug.zip](https://github.com/HomeOfAviSynthPlusEvolution/DelogoHD/files/7191268/delogohd-bug.zip)

The problem was discovered in the DelogoHD Doom9 thread: https://forum.doom9.org/showthread.php?p=1952476#post1952476

**Comment by msg7086** [comment]
Confirmed, mod2 padding issue.

    DelogoHD(logofile="test 1280x720-bad.lgd", top=-2)

Setting top = -2 would counter fix the padding error. Give me some time to find and fix the issue.

**Comment by msg7086** [comment]
a85dbde should have fixed the issue, can you confirm?

There's also a memory leak on VapourSynth fix, so please also let me know if there are memory related side effects.

**Comment by Reel-Deal** [comment]
> [a85dbde](https://github.com/HomeOfAviSynthPlusEvolution/DelogoHD/commit/a85dbde7e464a4ab9acaa4a522edba6f4dee4608) should have fixed the issue, can you confirm?

Do you mind compiling a test version?  I don't have  MSVC installed.

**Comment by msg7086** [comment]
I pre-released r11 with latest changes.

**Comment by Reel-Deal** [comment]
That fixed the problem, I even created an lgd with all odd values and it works fine. Thank you for fixing the issue 😃 

Closing the issue. If I noticed something else I will re-open.
