### ISSUE TITLE
Feature request: function to return logo position and dimension values

### ISSUE THREAD

**Issue by Reel-Deal** [msg7086/DelogoHD#4]
I have a feature request if it's not too complicated to implement. Putin modified Delogo back in 2014 and added a function named "InfoLogo" that returned the logo's position and dimension values as an integer.

The following was translated from: http://putin999.blog.fc2.com/blog-entry-78.html

The InfoLogo function has been added.
You can get the Left, Top, Width, and Height values of the logo data.

`logo_left = InfoLogo(logofile, info="Left")`
`logo_top = InfoLogo(logofile, info="Top")`
`logo_width = InfoLogo(logofile, info="Width")`
`logo_height = InfoLogo(logofile, info="Height")`

`#Crop the logo range (*For YV12, you need to change everything to a multiple of 2)`
`Crop(logo_left,logo_top,logo_width,logo_height)`

The download link is no longer active on that page but I have the source code if interested: [delogo0004src.zip](https://github.com/HomeOfAviSynthPlusEvolution/DelogoHD/files/7193014/delogo0004src.zip)
 
InfoLogo is a bad name, LogoInfoHD sounds much better if you choose to implemented 🤣

**Comment by msg7086** [comment]
Try r12.

    subtitle(Format("Left {} Top {} Width {} Height {}", delogohd_left, delogohd_top, delogohd_width, delogohd_height))

**Comment by Reel-Deal** [comment]
Nice! Can you please upload a binary for r12?

**Comment by msg7086** [comment]
https://github.com/HomeOfAviSynthPlusEvolution/DelogoHD/releases/tag/r12

**Comment by Reel-Deal** [comment]
Thank you :) ... Gonna to go test it

**Comment by msg7086** [comment]
I just corrected the variable names.

**Comment by Reel-Deal** [comment]
Ok just did a quick test and the numbers are not the same as in LogoScan.

LogoScan: x - 1132, y - 30, width - 90, height - 46
DelogoHD: left - 1120, top - 30, width - 128, height - 46

lgdeditor also shows the same values as LogoScan:
![lgdeditot](https://user-images.githubusercontent.com/3104705/133967917-b1e70eea-352f-42db-ae39-5138dbae5e5c.png)

**Comment by msg7086** [comment]
Yea it was the corrected size. Let me change it to return the raw size.

**Comment by msg7086** [comment]
Check r12a in releases.

**Comment by Reel-Deal** [comment]
It's all good now. Thank you for implementing that option. 
`Crop(delogohd_left, delogohd_top, delogohd_width, delogohd_height)`
Is much cleaner than having to call a function 4 times. Kudos 👍🏼 

Edit: I'll leave the issue open just in case and will close it if nothing else pops up.

**Comment by Reel-Deal** [comment]
One final request, can you make the exported variables global so they can be used inside of a function?

**Comment by msg7086** [comment]
I was hesitating of doing that because if you run multiple delogos it will be difficult to isolate the variables. I would rather let you define globals yourself.

**Comment by Reel-Deal** [comment]
Yeah, I guess in videos that have A logo and semi-transparent overlays in other places you would need two instances of DelogoHD.
